import os


# Default Superadmin
DEFAULT_SUPERADMIN_NAME = os.getenv('DEFAULT_SUPERADMIN_NAME')
DEFAULT_SUPERADMIN_EMAIL = os.getenv('DEFAULT_SUPERADMIN_EMAIL')
DEFAULT_SUPERADMIN_MSISDN = os.getenv('DEFAULT_SUPERADMIN_MSISDN')
DEFAULT_SUPERADMIN_PASSWORD = os.getenv('DEFAULT_SUPERADMIN_PASSWORD')


# SECRETS
JWT_SECRET = os.getenv('JWT_SECRET')
JWT_EXPIRY_HOURS = 3


# DB
POSTGRES_DB = os.getenv('POSTGRES_DB')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')

SQLALCHEMY_DATABASE_URL_ASYNC = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'


# Logging
MAX_LOG_BYTES = 1 * 1024 * 30 # 30MB
MAX_LOG_BACKUPS = 1

PORTAL_API_LOG_FILE = '/var/log/jubilee_claims_processing/portal_api.log'
